language: python
python:
  - "3.4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 
install:
  - pip install django
  - pip install selenium==2.53.6
  - pip install flake8
  - pip install autopep8
script:
  - python -m compileall ./superlists/*
  - flake8 --max-line-length=160  	./superlists/*
  - python3 -m doctest ./superlists/functional_tests.py
  - python3  	./superlists/functional_tests.py
  - python3 ./superlists/manage.py test
