language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install flake8
  - pip install autopep8
script:
  - flake8 --max-line-length=160  	superlists/functional_tests.py
  - python3  	superlists/functional_tests.py
