language: python
python:
  - "3.4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 
install:
  - pip install django
  - pip install selenium==2.53.6
  - pip install flake8
  - pip install autopep8
script:
  - cd ./superlists
  - python3 manage.py runserver
  - python -m compileall *
  - flake8 --max-line-length=160  	functional_tests.py lists/*
  - python3  	functional_tests.py
  - python3 manage.py test
