language: python
python:
  - "3.4"
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 
 - sudo apt-get update
 - sudo apt-get install -y --force-yes apache2
 - sudo /etc/init.d/apache2 restart
addons:
  - firefox: "49.0"
install:
  - pip install django==1.7 selenium==2.39 flake8 autopep8
  - sudo apt-get install nginx
  - sudo service nginx start
script:
  - cd ./superlists
  - wget -O bootstrap.zip https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip
  - unzip bootstrap.zip
  - mkdir -p lists/static
  - mv dist lists/static/bootstrap
  - rm bootstrap.zip
  - python -m compileall *
  - flake8 --max-line-length=160 functional_tests/ lists/
  - python3 manage.py test lists/
  - python3 manage.py test functional_tests/
