python:
  - "3.4"
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  
addons:
  - firefox
  
install:
  - pip install django==1.7
  - pip selenium==2.39
  - pip flake8 autopep8

script:
  - cd ./superlists
  - wget -O bootstrap.zip https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip
  - unzip bootstrap.zip
  - mkdir -p lists/static
  - mv dist lists/static/bootstrap
  - rm bootstrap.zip
  - python -m compileall *
  - flake8 --max-line-length=160 --exclude migrations,test_views.py ./
  - python3 manage.py test lists/
  #- python3 manage.py test functional_tests/
